### ISSUE TITLE
Если из-за вас заблокируют github?

### ISSUE THREAD

**Issue by aliskhanoff** [smartvotedocs/votesmart2021#105]
Уважаемые ФБК и сторонники УГ. ЗДЕСЬ НЕ МЕСТО ДЛЯ ПОЛИТИКИ. У нас свой мир! Есть куча сторонних сервисов с подобным функционалом, например https://bitbucket.com. Они в Канадцы (вроде) и они не так популярны! Вот  [тут](https://www.moyo.ua/news/10-luchshikh-oblachnykh-servisov-khraneniya-informatsii.html) ещё куча сервисов. Спасибо

**Comment by 0loli** [comment]
Если заблокируют гитхаб, у тебя появится время пойти и проголосовать за тех, кто не заблокирует. Все просто
