### ISSUE TITLE
эпическая битва

### ISSUE THREAD

**Issue by tyashin** [smartvotedocs/votesmart2021#107]
РФ vs УГ.  Битва дух говн.

**Comment by DmitrySidorow** [comment]
+ 15 рублей

**Comment by tyashin** [comment]
Беспомощный аргумент ad hominem. Старайтесь лучше.

**Comment by tyashin** [comment]
Проблема не в ЕР и, конечно, не в сомнительной мотивации создателей проекта УГ (пишут, что Волков держит вас за хомячков, но я свечку не держал, конечно). 
Основных проблем две:
1. Необразованная, конфомистская, лишенная чувства собственного достоинства (90+%) публика в РФ. Избиратели, ЕР, КПРФ и т.д. - незачем менять одно г. на другое - все возьмут под козырек и сделают, как их начальство попросит. В принципе, это не исключительно свойство РФ (в UK примерно также, например, с поправкой на небольшие культурные отличия, конечно.)
2. Допустим, либералы победили и в РФ установилась белая и пушистая демократия древнегреческого образца (а что,  гулять так гулять).  Допустим, страна не сползла сразу же в тот левацкий пц, который творится сейчас на Западе (woke-культура, MeToo, снос статуй,  радикальный феминизм и т.п.). Пусть будет идеальная демократия уровня начала 90-х на Западе. Ваш массовый избиратель демократически выберет лидеров, которые наиболее способствуют достижению целей этого избирателя. Цели заложены эволюционно - размножиться, захватить побольше ресурсов, потребить больше товаров и достичь комфорта. К сожалению, массовый Homo sapiens никогда не откажется от этого сценария (он не может, т.к. создан таким). Но этому сценарию уже совсем недолго осталась, т.к. человеческая популяция уже на порядок превышает свою оптимальную численность, создавая избыточное давление на экосистемы. Я бы сказал, мы увидим печальный конец этой модели уже в ближайшие 10-15 лет. Либо так, либо кто-то (что-то) возьмет человечество под полный контроль. Это мог бы быть "benevolent strong AI", например, если мы не поубиваем  друг друга на пути к его созданию. Он, теоретически, мог бы контролировать и заботиться о нас, как мы заботимся о котиках, например - "стоять над пропастью во ржи".  К сожалению, этот минимально оптимистический сценарий крайне маловероятен, кмк.

**Comment by tyashin** [comment]
Беспомощный аргумент ad hominem. Старайтесь лучше.

Проблема не в ЕР и, конечно, не в сомнительной мотивации создателей проекта УГ (пишут, что Волков держит вас за хомячков, но я свечку не держал, конечно).

Основных проблем две:

1. Необразованная, конформистская, лишенная чувства собственного достоинства публика в РФ. ЕР, КПРФ и т.д. - незачем менять одно г. на другое - все возьмут под козырек и проголосуют, как их начальство в Кремле попросит. В принципе, такая сервильность, это не исключительное свойство РФ.
2. Допустим, либералы победили, и в РФ установилась белая и пушистая демократия. Допустим, страна не сползла сразу же в тот левацкий пц, который творится сейчас на Западе (woke культура, MeToo, снос статуй, радикальный феминизм, деплатформинг, канселлинг и т.п.). Пусть будет демократия уровня начала 90-х на Западе. Ваш массовый избиратель демократически выберет лидеров, которые наиболее способствуют достижению целей этого избирателя. Цели заложены эволюционно: размножиться, захватить побольше ресурсов, потребить больше товаров и достичь комфорта. К сожалению, массовый Homo sapiens сам никогда не откажется от этого сценария (он не сможет, т.к. создан таким). Но этому сценарию уже совсем недолго осталось, т.к. человеческая популяция уже на порядок превышает свою оптимальную численность, создавая избыточное давление на экосистемы. Я бы предположил, что мы увидим печальный конец этой модели уже в ближайшие 10-15 лет. Либо так, либо кто-то (что-то) возьмет человечество под полный контроль. Это мог бы быть "benevolent strong AI", например, если мы не поубиваем друг друга на пути к его созданию. Однако, этот оптимистический сценарий крайне маловероятен, кмк.
