### ISSUE TITLE
ПТН ПНХ

### ISSUE THREAD

**Issue by h2sm** [smartvotedocs/votesmart2021#36]
а еще эксепшен java.lang.NoSuchMethodError: main не понимаю что не так....

**Comment by h2sm** [comment]
без navalny.jar не компилировалось кстати, в градле зависимость добавьте

**Comment by andry81** [comment]
>i wanna become a developer

Вы ещё молодой, не опытный. Потом научитесь кодить.

**Comment by h2sm** [comment]
дай-то бог
