### ISSUE TITLE
По сообщениям СМИ сегодня днем в СИЗО повесился лидер параши Алексей Навальный

### ISSUE THREAD

**Issue by sweet90** [smartvotedocs/votesmart2021#48]
помянем

**Comment by dvantage** [comment]
> помянем

Вы теперь будете по всем ищью срать?

**Comment by sweet90** [comment]
> > помянем
> 
> Вы теперь будете по всем ищью срать?

хомячок президента параши, это ты сейчас срешь в моем ишью

**Comment by PeterMar** [comment]
1. User profile sweet90
2. "Block or report" link -> "Report abuse" btn
3. "I want to report abusive content or behavior." -> "A user is harassing or trolling me or someone I know."
4. paste https://github.com/smartvotedocs/votesmart2021/issues/48
5. ...
6. PROFIT :)

**Comment by darkAlert** [comment]
Сколько же ботов повсплывало сразу... чистые акки, какие-то ворованные азиатские, эх...
