### ISSUE TITLE
Расходимся, нас обманули

### ISSUE THREAD

**Issue by KrakeN0O0** [smartvotedocs/votesmart2021#69]
Предлагают демократию, принуждая выбрать их кандидатов. Хоть это и единственный способ сдвинуть едро, но демократией не пахнет)

**Comment by iaroslav-korenskoi** [comment]
ДОБРОВОЛЬНОЕ объединение людей против общего врага — и есть демократия.

**Comment by Sergey3912** [comment]
Демократия это не значит сидеть и сложить лапки, чтобы никого не обидеть вдруг. Никакой свободы врагам свободы.

**Comment by KrakeN0O0** [comment]
Демокра́тия — политическая система, в основе которой лежит метод коллективного принятия решений с равным воздействием участников на исход процесса или на его существенные стадии

Коллективное принятие решений, а не когда за вас приняли, а вам только галочку поставить) А вы тут задизлайкали, разбуйствовались
Я не отрицаю, что смена правительства уже давно нужна, и что по факту такой способ - единственный, чтобы хоть что то поменять.

**Comment by iaroslav-korenskoi** [comment]
>  метод коллективного принятия решений

Вот мы коллективно сами и согласились с тем, чтобы нам показали список.
Мы сами и хотим коллективно и главное ЭФФЕКТИВНО проголосовать.
Так, чтобы голоса были аккумулированы на одном кандидате, а не размазаны по нескольким.
Это наш коллективный демократический выбор.

Нас никто не заставляет голосовать по этому списку.
Не принуждает. Как и положено по демократии — мы можем согласиться, а можем не согласиться с рекомендациями УмГ. В этом и суть демократии, что мы сами коллективно выбираем, как мы хотим поступить.

**Comment by andry81** [comment]
> Коллективное принятие решений, а не когда за вас приняли, а вам только галочку поставить)

А разве все предыдущие голосования не такими же были, когда за нас выбрали каких кандидатов допускать, а нам только галочку поставить? Или это другое?

**Comment by iaroslav-korenskoi** [comment]
>  все предыдущие голосования не такими же были

Будьте внимательнее, мой виз-а-ви, я не зря написал про ЭФФЕКТИВНОЕ голосование, и аккумулирование максимального количества голосов на одном кандидате, не лишая других права голосовать как им угодно. Это и есть демократия. Что МЫ ХОТИМ объединиться эффективно, нам показали инструмент, и мы выбрали им воспользоваться (ну, кто-то не выбрал, это их право).

Не за нас выбрали. А нам ПРЕДЛОЖИЛИ. 
За нас провели огромную работу, по анализу кандидатов, и определению наиболее перспективных и эффективных вариантов. 

Не нравится? Ок, не голосуй как предлагает УмГ. 
Поддерживаешь идею аккумулирования единой силой? Тогда голосуй за предложенного, т.к. вместе мы сила.

**Comment by andry81** [comment]
> Будьте внимательнее, мой виз-а-ви

Я и не Вам отвечал.

**Comment by iaroslav-korenskoi** [comment]
> Я и не Вам отвечал.

Пардон, виноват. В изобилии споров с набежавшими — перепутал.
