### ISSUE TITLE
я конечно все понимаю, но гитхаб не для этого создан

### ISSUE THREAD

**Issue by DjamikTea** [smartvotedocs/votesmart2021#70]

**Comment by gmankab** [comment]
гитхаб создан для публикации информации

**Comment by DjamikTea** [comment]
> гитхаб создан для публикации информации

GitHub — крупнейший веб-сервис для хостинга IT-проектов и их совместной разработки.

**Comment by deflorator1980** [comment]
У вас больше звёзд и форков? ;)

**Comment by andry81** [comment]
> > гитхаб создан для публикации информации
> 
> GitHub — крупнейший веб-сервис для хостинга IT-проектов и их совместной разработки. [ист](https://ru.wikipedia.org/wiki/GitHub)

Ну Вы пока ещё ни один не разработали, но мнение уже имеете.

**Comment by DjamikTea** [comment]
> > > гитхаб создан для публикации информации
> > 
> > 
> > GitHub — крупнейший веб-сервис для хостинга IT-проектов и их совместной разработки. [ист](https://ru.wikipedia.org/wiki/GitHub)
> 
> Ну Вы пока ещё ни один не разработали, но мнение уже имеете.

на источник нажмите пожалуйста

**Comment by gmankab** [comment]
ну и хули ты тогда заходишь сюда ныть, если это сервис только для разработки и хостинга

**Comment by andry81** [comment]
> на источник нажмите пожалуйста

У Вас ни одного репозитория в источниках.

**Comment by DjamikTea** [comment]
> ну и хули ты тогда заходишь сюда ныть, если это сервис только для разработки и хостинга

потому что это абсурд выкладывать сюда на гитхаб. Для этого существуют Гугл таблицы и тд

Еще хочу сказать, что я ничего **не имею против** Навального и его деятельности.

**Comment by andry81** [comment]
> Какой еще репозиторий
> 
> > [ист](https://ru.wikipedia.org/wiki/GitHub)

github.com/DjamikTea?tab=repositories&type=source

**Comment by gmankab** [comment]
> Для этого существуют Гугл таблицы
когда сюда это залили гугл таблицы не работали в россии

**Comment by DjamikTea** [comment]
> > Какой еще репозиторий
> > > [ист](https://ru.wikipedia.org/wiki/GitHub)
> 
> https://github.com/DjamikTea?tab=repositories&type=source

я имел ввиду источник на википедию

**Comment by egornovivan** [comment]
> [ист](https://ru.wikipedia.org/wiki/GitHub)

И? Может на следующие выборы список будет пополняться через пуллреквесты, а гит как и положено будет использоваться для контроля версий
![Screenshot_20210917-013238_Trebuchet](https://user-images.githubusercontent.com/60801856/133682124-9d6458eb-1a2f-42d2-bd14-d92c2a76ee32.png)

**Comment by andry81** [comment]
> 
> я имел ввиду источник на википедию

И опять мимо: https://en.wikipedia.org/wiki/GitHub

```
It is commonly used to host open-source projects.
```

**Comment by DjamikTea** [comment]
честно, это странное решение выкладывать на гитхаб список кандидатов на выборы

**Comment by DjamikTea** [comment]
Извините, я нашел причину почему они выложили на гитхаб
