### ISSUE TITLE
1101000010011101110100001011000011010000101100101101000010110000110100001011101111010001100011001101000010111101110100011000101111010000101110010010000011100010100000000010000011010000101100101101000010111110110100011000000000100001

### ISSUE THREAD

**Issue by Highlight37** [smartvotedocs/votesmart2021#86]
Принципиально теперь проголосую за Единую Россию во всех бюллетенях. До этого на выборы идти не хотел вообще. Но теперь пойду.

Да хотя бы потому, что вы вывалили свои убогие списки на Гуглодокументы и сюда. Вы прекрасно понимали, что возможно в результате этого данные сервисы будут иметь проблемы с доступом. Но на интересы своих же соотечественников славные создатели "Прекрасной России Будущего" как-то поклали. Страшно подумать, что будет, если вы получите власть.

**Comment by Highlight37** [comment]
UPD: Но власть вы никогда не получите, к счастью.

**Comment by VanyaErohin** [comment]
@Highlight37 настолько неравнодушен к github, что зарегистрировался только сейчас

**Comment by Highlight37** [comment]
@VanyaErohin ты, как зарегистрировавшийся давно, должен знать о возможности скачивания файлов здесь без регистрации и sms. А другого мне гитхаба и не надо было ровно до того момента, пока не захотелось оставить коммент по поводу размещения smartvotedocs. :)

**Comment by mdashlw** [comment]
Путин блокирует весь интернет, чтобы запретить Умное голосование, но виноват всё равно Навальный

**Comment by Volifter** [comment]
`11010000100100101101000010111110110100011000000000100000110100001011001000100000110100001011101011010001100000001101000010110101110100001011110011010000101110111101000010110101001000001101000110000001110100001011100011010000101101001101000010111000110100011000001000101110`

А у тебя, умник, байта на 21-й позиции не хватает.

**Comment by Highlight37** [comment]
@Volifter, но суть-то от этого не меняется. ;)

**Comment by andry81** [comment]
> Принципиально теперь проголосую за Единую Россию

Назло бабушке отморозишь уши?

**Comment by JoCat** [comment]
> Вы прекрасно понимали, что возможно в результате этого данные сервисы будут иметь проблемы с доступом.

Если вы здесь зарегистрированы не просто так, и что-то да понимаете в разработке, должны прекрасно знать про такую штуку как VPN 😏

**Comment by Highlight37** [comment]
@JoCat, имею подписку на 1 из подобных сервисов, 1 на всякий случай висит на собственной VPS, еще иногда shadowsocks использовую. Но блин, зачем лезть в окно, если есть вход через калитку? Ну т.е. вот сейчас я могу сюда или, скажем, или в Гуглдокс зайти БЕЗ VPN или прокси. Но по вине некоторых личностей, которые постят контент, подобный вот этому Смартвоуту мне и еще многим людям придется ходить на этот (или какой-то иной популярный сервис) ЧЕРЕЗ VPN или прокси.

Вот у меня в эпоху, когда локалки провайдеров со всякими "сервисами" были актуальны, случай был. На местном IRC-сервере один придурок флудил без устали на одном канале. Так IRCопы не стали с ним возиться и забанили к чертям всю подсеть. Недовольных было достаточно. Я не помню, чем закончилась история, но факт в том, что из за одного человека пострадало минимум пара десятков.

Вот я и не понимаю, почему команда господина Навального не использует какие-то свои ресурсы для распространения материалов. Или деньги на регистрацию доменов и хостинг кончились?

Впрочем, ладно. Это так... IMHO. :)

**Comment by Highlight37** [comment]
@andry81, тут скорее не за Единую Россию, а против УМГ. Не нравится мне эти люди, претендующие на власть. Пусть уже лучше все как есть останется. Так что с ушами моими все будет в полном порядке.

**Comment by 0loli** [comment]
>Пынявый режим блокирует интернеты
>АРЯЯЯЯ НАВАЛЬНЫЙ В ШТАНЫ НАСРАЛ!!! КАК ЖЕ МНЕ ТЕПЕРЬ НА ПЕТУХХАБ ЗАХОДИТЬ????
