### ISSUE TITLE
рашка говно

### ISSUE THREAD

**Issue by regedit9** [smartvotedocs/votesmart2021#89]
Скорее бы уехать из этой ублюдочной страны

**Comment by maidrrr** [comment]
> Скорее бы уехать из этой ублюдочной страны

Нахуй такие как ты в других странах?:)

**Comment by regedit9** [comment]
> Нахуй такие как ты в других странах?:)
Лахта, спок

**Comment by regedit9** [comment]
> Нахуй такие как ты в других странах?:)

Лахта, спок

**Comment by maidrrr** [comment]
> > Нахуй такие как ты в других странах?:)
> 
> Лахта, спок

Я вообще не из России )

**Comment by regedit9** [comment]
> Я вообще не из России )

И при этом копротивляешься за пидорашку

**Comment by ultrasaks** [comment]
эх тупая рашка рашка парашка свалить бы....

**Comment by maidrrr** [comment]
> > Я вообще не из России )
> 
> И при этом копротивляешься за пидорашку

А почему конкретно за неё. Я просто считаю говном тех не любит свою страну, вот и всё.

**Comment by regedit9** [comment]
> > > Я вообще не из России )
> > 
> > 
> > И при этом копротивляешься за пидорашку
> 
> А почему конкретно за неё. Я просто считаю говном тех не любит свою страну, вот и всё.

Я не выбирал эту страну, программистишка. Если бы я родился в КНДР, я бы обязан был любить его?

**Comment by maidrrr** [comment]
> > > > Я вообще не из России )
> > > 
> > > 
> > > И при этом копротивляешься за пидорашку
> > 
> > А почему конкретно за неё. Я просто считаю говном тех не любит свою страну, вот и всё.
> 
> Я не выбирал эту страну, программистишка. Если бы я родился в КНДР, я бы обязан был любить его?

Вполне обязан.

**Comment by regedit9** [comment]
> > > > > Я вообще не из России )
> > > > 
> > > > 
> > > > И при этом копротивляешься за пидорашку
> > > 
> > > 
> > > А почему конкретно за неё. Я просто считаю говном тех не любит свою страну, вот и всё.
> > 
> > 
> > Я не выбирал эту страну, программистишка. Если бы я родился в КНДР, я бы обязан был любить его?
> 
> Вполне обязан.

Кому обязан? Тебе никто ничего не обязан, программистишка
